### ISSUE TITLE
How is the projection vector p trainable?

### ISSUE THREAD

**Issue by Yfhu1103** [HongyangGao/gunet#4]
Hi, In your "ops.py" line 89~line 107, you define graph pool. But it seems to be that you have missed the gate step, i.e. scores should be multiplied to X, but I do not see this step in your code. Could do please explain how the projection vector is trainable? Thank you!

**Comment by HongyangGao** [comment]
Hi, thank you for pointing it out. It seems I uploaded the wrong version. I have updated the code. Thank you.

**Comment by Yfhu1103** [comment]
I used the previous codes and new codes to do the graph classification task and I get the similar results as shown in the paper, I do not understand why, is it make sense?

**Comment by HongyangGao** [comment]
Hi, I think it's interesting. But since the p is not trainable, it should
stay the same all the time. That means it can be considered as a fixed
composition pattern.

For example, c = 2a + 3b, where 2 and 3 are fixed weights. This means the
network may train the GCN part to make the resulting ranking scores useful
in pooling.

Also, the architecture of the U-Net should mostly benefits the performance
instead of just relying a projection vector p.

Best,

Hongyang

**Comment by Yfhu1103** [comment]
Thanks for explaination
